name:                gui

dependencies:
- base
- shared
- record-hasfield
- record-dot-preprocessor
- miso
- miso-spa
- miso-styled
- miso-http
- clay
- aeson
- jsaddle

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-unused-do-bind

default-extensions:
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  gui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gui
