name:                gui

dependencies:
- base >= 4.7 && < 5
# - shared
- record-hasfield
- miso
- miso-spa
# - miso-styled
# - miso-http
- clay
- aeson
- jsaddle

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-unused-do-bind

default-extensions:
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  gui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gui
