name:                shared

dependencies:
- base
- record-hasfield
- text
- miso
- miso-spa
- aeson

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-unused-do-bind
- -Wno-orphans

default-extensions:
- OverloadedStrings
- LambdaCase
- DeriveGeneric
- TypeSynonymInstances

library:
  source-dirs: src
