name:                api

dependencies:
- base
- shared
- record-hasfield
- servant
- servant-server
- servant-swagger
- servant-swagger-ui
- swagger2
- aeson
- aeson-injector
- warp
- wai
- wai-cors
- raven-haskell
- bytestring
- exceptions
- fast-logger
- time
- text
- wai-logger
- resource-pool
- postgresql-simple
- postgresql-simple-migration
- qm-interpolated-string
- transformers
- yaml
- miso
- miso-spa

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-unused-do-bind
- -Wno-orphans

default-extensions:
- OverloadedStrings
- LambdaCase
- DataKinds
- TypeOperators
- DeriveGeneric

library:
  source-dirs: src

executables:
  api:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
